# Form implementation generated from reading ui file 'edit_config_class.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(610, 475)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetMaximumSize
        )
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_load_config = QtWidgets.QPushButton(parent=Form)
        self.button_load_config.setObjectName("button_load_config")
        self.horizontalLayout_2.addWidget(self.button_load_config)
        self.button_save_config = QtWidgets.QPushButton(parent=Form)
        self.button_save_config.setObjectName("button_save_config")
        self.horizontalLayout_2.addWidget(self.button_save_config)
        self.button_add_border = QtWidgets.QPushButton(parent=Form)
        self.button_add_border.setObjectName("button_add_border")
        self.horizontalLayout_2.addWidget(self.button_add_border)
        self.button_add_detect_window = QtWidgets.QPushButton(parent=Form)
        self.button_add_detect_window.setObjectName("button_add_detect_window")
        self.horizontalLayout_2.addWidget(self.button_add_detect_window)
        self.button_process = QtWidgets.QPushButton(parent=Form)
        self.button_process.setObjectName("button_process")
        self.horizontalLayout_2.addWidget(self.button_process)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.frame_viewer = QtWidgets.QGraphicsView(parent=Form)
        self.frame_viewer.setObjectName("frame_viewer")
        self.verticalLayout_2.addWidget(self.frame_viewer)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalSlider = QtWidgets.QSlider(parent=Form)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 5)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.action_save_config = QtGui.QAction(parent=Form)
        self.action_save_config.setCheckable(True)
        self.action_save_config.setObjectName("action_save_config")
        self.action_open_config = QtGui.QAction(parent=Form)
        self.action_open_config.setCheckable(True)
        self.action_open_config.setObjectName("action_open_config")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_load_config.setText(_translate("Form", "Load config"))
        self.button_save_config.setText(_translate("Form", "Save config"))
        self.button_add_border.setText(_translate("Form", "Add Border"))
        self.button_add_detect_window.setText(_translate("Form", "Add exit indicator"))
        self.button_process.setText(_translate("Form", "Process"))
        self.action_save_config.setText(_translate("Form", "Save config"))
        self.action_save_config.setShortcut(_translate("Form", "Ctrl+S"))
        self.action_open_config.setText(_translate("Form", "Open config"))
        self.action_open_config.setShortcut(_translate("Form", "Ctrl+O"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
