# Form implementation generated from reading ui file 'view_edit_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 523)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stacked_widget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.editing_page = QtWidgets.QWidget()
        self.editing_page.setObjectName("editing_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.editing_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.edit_config_widget = EditConfigWidget(parent=self.editing_page)
        self.edit_config_widget.setObjectName("edit_config_widget")
        self.gridLayout_2.addWidget(self.edit_config_widget, 0, 0, 1, 1)
        self.stacked_widget.addWidget(self.editing_page)
        self.viewing_page = QtWidgets.QWidget()
        self.viewing_page.setObjectName("viewing_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.viewing_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_video_button = QtWidgets.QPushButton(parent=self.viewing_page)
        self.add_video_button.setObjectName("add_video_button")
        self.horizontalLayout.addWidget(self.add_video_button)
        self.save_session_button = QtWidgets.QPushButton(parent=self.viewing_page)
        self.save_session_button.setObjectName("save_session_button")
        self.horizontalLayout.addWidget(self.save_session_button)
        self.load_session_button = QtWidgets.QPushButton(parent=self.viewing_page)
        self.load_session_button.setObjectName("load_session_button")
        self.horizontalLayout.addWidget(self.load_session_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 3)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.viewers_grid_layout = QtWidgets.QGridLayout()
        self.viewers_grid_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.viewers_grid_layout.setSpacing(0)
        self.viewers_grid_layout.setObjectName("viewers_grid_layout")
        self.gridLayout_4.addLayout(self.viewers_grid_layout, 1, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 15)
        self.stacked_widget.addWidget(self.viewing_page)
        self.mono_viewing_page = QtWidgets.QWidget()
        self.mono_viewing_page.setObjectName("mono_viewing_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mono_viewing_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mono_viewing_layout = QtWidgets.QGridLayout()
        self.mono_viewing_layout.setObjectName("mono_viewing_layout")
        self.gridLayout_3.addLayout(self.mono_viewing_layout, 0, 0, 1, 1)
        self.stacked_widget.addWidget(self.mono_viewing_page)
        self.gridLayout.addWidget(self.stacked_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_video_button.setText(_translate("MainWindow", "Add video"))
        self.save_session_button.setText(_translate("MainWindow", "Save session"))
        self.load_session_button.setText(_translate("MainWindow", "Load session"))
from editconfigwidget import EditConfigWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
